name: deploy
on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_VERSION: "ms202401i"

jobs:
  deploy-to-cluster:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ec2-44-220-157-212.compute-1.amazonaws.com

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Verify Changes are Checked Out
        run: |
          echo "Verifying changes..."
          git status
        continue-on-error: true  # Para que la ejecución no falle si git status no encuentra nada

      - name: Set Dockerfile WORKDIR to /app
        run: |
          sed -i 's/WORKDIR \/app/WORKDIR \/app/' Dockerfile

      - name: Verify Dockerfile WORKDIR
        run: |
          echo "Verifying Dockerfile WORKDIR..."
          cat Dockerfile | grep WORKDIR

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker Hub Login
        run: |
          echo "Verifying Docker Hub login..."
          docker info

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ms202401i:latest

      - name: Verify Docker Image Push
        run: |
          echo "Verifying Docker image push..."
          docker images
